GET http://localhost:3333/doacoes

###

POST http://localhost:3333/doacoes
Content-Type: application/json

{
    "pessoa_id": 2,
    "local_id": 1,
    "data": "1970-01-01T00:00:00.000Z"

}

###

PUT http://localhost:3333/doacoes
Content-Type: application/json

{
    "id": 2,
    "pessoa_id": 4,
    "local_id": 4,
    "data": "2023-01-01T00:00:00.000Z"
}
###


DELETE http://localhost:3333/doacoes
Content-Type: application/json

{
    "id": 3
}